include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_unnecessary_containers: false
    prefer_const_constructors: false
    unnecessary_null_comparison: false
    invalid_use_of_protected_member: false
