name: Build Web

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2
      - run: flutter pub get

      - run: flutter test test/unit_test.dart

<<<<<<< HEAD
      - run: flutter analyze --no-fatal-warnings --no-fatal-infos lib/
=======
      - run: flutter analyze --no-fatal-warnings --no-fatal-infos lib/templates/lab7/
>>>>>>> 9291205cb93b05ae6a556007fc10980a7b7a94ab

      - run: flutter build web --release lib/main.dart
      

      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          customArgs: "lib/main.dart"
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2
      - run: flutter pub get
      - run: flutter build windows --release lib/main.dart
